---
title: "Allende et al. 2017"
output: html_document
date: "2023-06-06"
---

#Libraries
```{r}
library(truncnorm)
library(fitdistrplus)
library(EnvStats)
library(mc2d)
library(ggplot2)
library(tidyverse)
```


```{r}
set.seed(100)
decay_effect<-c()
load_final<-c()
track_seed<-c()
for (i in 1:10000){
  Days<- round(rpert(1,32,36.8,43.0)) #winter round(rpert(1,51,56.7,67)) #Baseline round(rpert(1,32,36.8,43.0))
  Rain_Days<-rpert(1,1,5.6,14) 
  P_Sun <- 1 - Rain_Days/Days
  Sun <- rbinom(Days, 1, P_Sun)
  Ec0_soil <-rnorm(1,0.549,0.816)#*2
  P_Ec_Water<-0.35
  Ecoli_Irr_Water<-rbinom(Days,1,P_Ec_Water)
  C_Ecoli_Irr_Water<-(10^(rnorm(Days,0.604,0.357)))/100
  
  Trans_Irr_Water <-runif(Days, 1.8, 21.6)
  Sun_hrs<-rpert(Days, 5, 10.4,12)
  Irr_Splashing<-rpert(Days, 0.02, 0.04, 0.06)
  P_Irr_Splashing<-rbinom(Days, 1, Irr_Splashing)
  P_Rain_Spashing<-1
  Soil_Transfer<-rbetagen(Days, 0.4, 0.8, 0.05, 16.4)
  P_Bug_Plant<-runif(Days, 0.35, 0.9)
  C_Irr<-round(C_Ecoli_Irr_Water * Trans_Irr_Water* Ecoli_Irr_Water* Sun)
  C_RSp<-round(10^(Ec0_soil) * Soil_Transfer * P_Bug_Plant * P_Rain_Spashing * (1- Sun)) 
  C_IrrSp<-round(10^(Ec0_soil) * Soil_Transfer * P_Bug_Plant * P_Irr_Splashing * Sun)

  C_load<-C_Irr + C_RSp + C_IrrSp
  Sun_Decay<-0#(-0.52 * (Sun_hrs/24))#Baseline -0.52  #Sun Decay No solar −0.18 #winter - 0.48
  C_Final = ifelse(C_load>0, 10^(log10(C_load)+Sun_Decay),C_load)
  load_final<-c(load_final,sum(C_Final))
}

mean(load_final)
hist(log10(load_final))


#Baseline Scenario
Baseline_Scen<-load_final
#Sun_Decay
SunDecay_Scen<-load_final
#Sun Decay_No Solar
SunDecay_NoRad_Scen<-load_final
#Winter
Winter_Scen<-load_final
#No Rain
No_Rain_Scen<-load_final
# No Overhead Irrigation
No_Overhead<-load_final
#Increase soil contamination
Increase2_Soil_Cont<-load_final

df_effects<-data.frame("valueCFU" = c(Baseline_Scen,SunDecay_Scen,SunDecay_NoRad_Scen,Winter_Scen,No_Rain_Scen,No_Overhead,Increase2_Soil_Cont),
           "scenario" = c(rep("Baseline", 10000),rep("With Sun Decay", 10000) ,rep("With Sun Decay Low Rad", 10000), rep("Winter", 10000), rep("No Rain", 10000),rep("No OVerhead", 10000), rep("2X soil cont", 10000)) )

df_effects$logvalue = log10(df_effects$valueCFU)

df_effects %>% 
  ggplot(aes(x = logvalue, fill = scenario))+
  geom_density(alpha = 0.5)+
  theme_bw()+
  facet_wrap(~scenario)+
  labs( x = "Log CFU/g")



df_effects_quantiles<-data.frame("valueCFU" = c((quantile(log10(Baseline_Scen), seq(0.001,1,0.001))),
                                      (quantile(log10(SunDecay_Scen), seq(0.001,1,0.001))),
                                      (quantile(log10(SunDecay_NoRad_Scen), seq(0.001,1,0.001))),
                                      (quantile(log10(Winter_Scen), seq(0.001,1,0.001))),
                                      (quantile(log10(No_Rain_Scen), seq(0.001,1,0.001))),
                                      (quantile(log10(No_Overhead), seq(0.001,1,0.001))),
                                      (quantile(log10(Increase2_Soil_Cont), seq(0.001,1,0.001)))),
           "scenario" = c(rep("Baseline", 1000),rep("With Sun Decay", 1000) ,rep("With Sun Decay Low Rad", 1000), rep("Winter", 1000), rep("No Rain", 1000),rep("No OVerhead", 1000), rep("2X soil cont", 1000)),
           "quantile" = rep(seq(0.001,1,0.001),7))


df_effects_quantiles %>% 
  ggplot(aes( x = quantile, y = valueCFU, color = scenario))+
  geom_line(size= 1)+
  theme_bw()+
  labs(x = "Quantiles", y = "Log CFU/g")


df_effects_quantiles<-data.frame("valueCFU" = c((quantile(log10(Baseline_Scen), seq(0.001,1,0.001)))-(quantile(log10(Baseline_Scen), seq(0.001,1,0.001))),
                                      (quantile(log10(SunDecay_Scen), seq(0.001,1,0.001)))-(quantile(log10(Baseline_Scen), seq(0.001,1,0.001))),
                                     (quantile(log10(SunDecay_NoRad_Scen), seq(0.001,1,0.001)))-(quantile(log10(Baseline_Scen), seq(0.001,1,0.001))),
                                      (quantile(log10(Winter_Scen), seq(0.001,1,0.001)))-(quantile(log10(Baseline_Scen), seq(0.001,1,0.001))),
                                     (quantile(log10(No_Rain_Scen), seq(0.001,1,0.001)))-(quantile(log10(Baseline_Scen), seq(0.001,1,0.001))),
                                     (quantile(log10(No_Overhead), seq(0.001,1,0.001)))-(quantile(log10(Baseline_Scen), seq(0.001,1,0.001))),
                                      (quantile(log10(Increase2_Soil_Cont), seq(0.001,1,0.001)))-(quantile(log10(Baseline_Scen), seq(0.001,1,0.001)))),
           "scenario" = c(rep("Baseline", 1000),rep("With Sun Decay", 1000) ,rep("With Sun Decay Low Rad", 1000), rep("Winter", 1000), rep("No Rain", 1000),rep("No OVerhead", 1000), rep("2X soil cont", 1000)),
           "quantile" = rep(seq(0.001,1,0.001),7))


df_effects_quantiles %>% 
  ggplot(aes( x = quantile, y = valueCFU, color = scenario))+
  geom_line(size= 1)+
  theme_bw()+
  labs(x = "Quantiles", y = "Log CFU/g")




sd((quantile(log10(Baseline_Scen), seq(0.001,1,0.001)))-(quantile(log10(Baseline_Scen), seq(0.001,1,0.001))))
sd((quantile(log10(Baseline_Scen), seq(0.001,1,0.001)))-(quantile(log10(SunDecay_Scen), seq(0.001,1,0.001))))
sd((quantile(log10(Baseline_Scen), seq(0.001,1,0.001)))-(quantile(log10(SunDecay_NoRad_Scen), seq(0.001,1,0.001))))
sd((quantile(log10(Baseline_Scen), seq(0.001,1,0.001)))-(quantile(log10(Winter_Scen), seq(0.001,1,0.001))))
sd((quantile(log10(Baseline_Scen), seq(0.002,1,0.001)))-(quantile(log10(No_Rain_Scen), seq(0.002,1,0.001))), na.rm = T)
hist((quantile(log10(No_Overhead), seq(0.035,1,0.001)))-(quantile(log10(Baseline_Scen), seq(0.035,1,0.001))), na.rm = T)
sd((quantile(log10(Baseline_Scen), seq(0.035,1,0.001)))-(quantile(log10(Increase2_Soil_Cont), seq(0.035,1,0.001))), na.rm = T)


No_Rain_Scen[!is.na(No_Rain_Scen) & !is.infinite(No_Rain_Scen)]


hist(log10(Baseline_Scen), freq = F)
lines(x = density(x = log10(Baseline_Scen)), col = "red")
lines(x = density(x = log10(SunDecay_Scen)), col = "blue")
lines(x = density(x = log10(SunDecay_NoRad_Scen)), col = "green")
lines(x = density(x = log10(Winter_Scen)), col = "orange")
lines(x = density(x = log10(SunDecay_NoRad_Scen)), col = "pink")

hist((quantile(log10(SunDecay_Scen), seq(0.001,1,0.001))) - (quantile(log10(Baseline_Scen), seq(0.001,1,0.001))), na.rm = T)
hist((quantile(log10(SunDecay_NoRad_Scen), seq(0.001,1,0.001))) - (quantile(log10(Baseline_Scen), seq(0.001,1,0.001))), na.rm = T)

plot(quantile(log10(SunDecay_NoRad_Scen), seq(0,1,0.001)))


disdecay<-((quantile(log10(SunDecay_Scen), seq(0,1,0.001))) - (quantile(log10(Baseline_Scen), seq(0,1,0.001))))
disdecay<-na.omit(disdecay)
disdecay<-as.vector(disdecay)


dist_decay<-descdist(disdecay)

mean(SunDecay_Scen) mean(Baseline_Scen)

#Sun Decay Effect
SunDecay_Change<-log10(SunDecay_Scen) - log10(Baseline_Scen)
hist(SunDecay_Change)

#Sun Decay No Rad
SunDecay_NoRad_Change<-log10(SunDecay_NoRad_Scen) - log10(Baseline_Scen)
hist(SunDecay_NoRad_Change)

#Winter Effect
Winter_Change<-log10(Winter_Scen) - log10(Baseline_Scen)
hist(Winter_Change)

#No Rain
No_Rain_Change<-log10(No_Rain_Scen) - log10(Baseline_Scen)
hist(No_Rain_Change)


hist(decay_effect)
decay_effect<-na.omit(decay_effect)
decay_effect<-as.vector(decay_effect)
descdist(decay_effect)

fit.lnorm<-fitdist(-decay_effect, "gamma")
plot(fit.lnorm)

hist(-rgamma(10000,0.563200,3.427781))
```

